#pragma once

#define SPACE_HEIGHT 500.0f
#define SPACE_WIDTH 500.0f

#define ALIEN_HEIGHT 20.0f
#define ALIEN_WIDTH 20.0f

#define GUN_HEIGHT 20.0f
#define GUN_WIDTH 20.0f

#define BULLET_HEIGHT 5.0f
#define BULLET_WIDTH 5.0f

#define OBSTACLE_HEIGHT 5.0f
#define OBSTACLE_WIDTH 5.0f

#define NUMBER_OF_ALIENS_IN_LEVEL 11
#define NUMBER_OF_LEVELS 11

#define NUMBER_OF_OBSTACLES_IN_GROUP 10
#define NUMBER_OF_GROUPS 3

#define START_ALIEN_SPEED 1
#define GUN_SPEED 4
#define BULLET_SPEED 10

#define ALIEN_HIT_POINTS 1
#define GUN_HIT_POINTS 1
#define BULLET_HIT_POINTS 1
#define OBSTACLE_HIT_POINTS 1

#define ALIEN_RAPIDITY 1
#define GUN_RAPIDITY 1

#define START_NUMBER_OF_LIFES 3

#define BULLET_DAMAGE 1
